name: Update  Podcasts

on:
  push:
    branches: ["main"]
    paths:
      - 'podcasts.php'
  schedule:
    - cron: '20 7-23/3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-podcasts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run podcast parser
        run: php podcasts.php

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add podcasts.html
          git commit -m "Auto-update podcasts.html" || echo "No changes"

      - name: Push changes
        run: git push
