name: Update  Youtube

on:
  push:
    branches: ["main"]
    paths:
      - 'youtube.php'
  schedule:
    - cron: '30 6-23/4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-youtube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run youtube parser
        run: php youtube.php

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add youtube.html
          git commit -m "Auto-update youtube.html" || echo "No changes"

      - name: Push changes
        run: |
          git pull --rebase origin main
          git push
